language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --group=Parameters --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v